# Generated by Django 2.2 on 2021-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
    ]
