# Generated by Django 2.2 on 2021-02-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 2, 7, 20, 26, 31, 569894), max_length=8),
        ),
    ]
