# Generated by Django 2.2 on 2021-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_medinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Height(in cm)'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Weight(in kg)'),
        ),
    ]
