# Generated by Django 2.2 on 2021-02-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210214_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medinfo',
            name='donate',
        ),
        migrations.AddField(
            model_name='profile',
            name='donate',
            field=models.BooleanField(default=False, verbose_name='Willing to donate?'),
        ),
    ]
