# Generated by Django 2.2 on 2021-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210218_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='is_athlete',
            field=models.BooleanField(default=False, verbose_name='Are you an Athlete:'),
        ),
        migrations.AddField(
            model_name='medinfo',
            name='pulse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pulse rate'),
        ),
        migrations.AddField(
            model_name='medinfo',
            name='score',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
