# Generated by Django 2.2 on 2021-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210317_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='pulse',
            field=models.IntegerField(blank=True, default=50, max_length=3, null=True, verbose_name='Pulse rate'),
        ),
    ]
