# Generated by Django 2.2 on 2021-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210317_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='medinfo',
            name='bmi_grade',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='pulse',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='Pulse rate'),
        ),
    ]
