# Generated by Django 2.2 on 2021-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210319_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='bmi_grade',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
