# Generated by Django 2.2 on 2021-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210320_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='fever',
            field=models.BooleanField(default=False, verbose_name='Are you ill/Having Cold?'),
        ),
        migrations.AddField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('Very often', 'S'), ("Don't remember the last time I got", 'NN'), ('Once in a while', 'N')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
