# Generated by Django 2.2 on 2021-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210322_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('NN', "Don't remember the last time I got"), ('S', 'Very Often'), ('N', 'Once in a while')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
