# Generated by Django 2.2 on 2021-03-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210322_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Hypermetropia', 'Difficult in reading'), ('Glasses', 'I wear Glasses'), ('Myopia', 'Difficult to see distant objects'), ('Normal', 'I can see clearly'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
    ]
