# Generated by Django 2.2 on 2021-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210323_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hip(in cm)'),
        ),
        migrations.AddField(
            model_name='medinfo',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waist(in cm)'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Myopia', 'Difficult to see distant objects'), ('Presbyopia', 'Difficulty in both'), ('Hypermetropia', 'Difficult in reading'), ('Normal', 'I can see clearly'), ('Glasses', 'I wear Glasses')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('N', 'Once in a while'), ('NN', "Don't remember the last time I got"), ('S', 'Very Often')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
