# Generated by Django 2.2 on 2021-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210323_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='whr',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Myopia', 'Difficult to see distant objects'), ('Normal', 'I can see clearly'), ('Hypermetropia', 'Difficult in reading'), ('Glasses', 'I wear Glasses'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('S', 'Very Often'), ('N', 'Once in a while'), ('NN', "Don't remember the last time I got")], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
