# Generated by Django 2.2 on 2021-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210323_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Normal', 'I can see clearly'), ('Glasses', 'I wear Glasses'), ('Myopia', 'Difficult to see distant objects'), ('Hypermetropia', 'Difficult in reading'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
    ]
