# Generated by Django 2.2 on 2021-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210323_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Hypermetropia', 'Difficult in reading'), ('Glasses', 'I wear Glasses'), ('Myopia', 'Difficult to see distant objects'), ('Normal', 'I can see clearly'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('S', 'Very Often'), ('NN', "Don't remember the last time I got"), ('N', 'Once in a while')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
