# Generated by Django 2.2 on 2021-03-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210323_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Myopia', 'Difficult to see distant objects'), ('Hypermetropia', 'Difficult in reading'), ('Normal', 'I can see clearly'), ('Presbyopia', 'Difficulty in both'), ('Glasses', 'I wear Glasses')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
    ]
