# Generated by Django 2.2 on 2021-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210323_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='whr_grade',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Glasses', 'I wear Glasses'), ('Myopia', 'Difficult to see distant objects'), ('Hypermetropia', 'Difficult in reading'), ('Normal', 'I can see clearly'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('NN', "Don't remember the last time I got"), ('N', 'Once in a while'), ('S', 'Very Often')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
