# Generated by Django 2.2 on 2021-03-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210324_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Myopia', 'Difficult to see distant objects'), ('Normal', 'I can see clearly'), ('Hypermetropia', 'Difficult in reading'), ('Presbyopia', 'Difficulty in both'), ('Glasses', 'I wear Glasses')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('N', 'Once in a while'), ('NN', "Don't remember the last time I got"), ('S', 'Very Often')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='whr',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
    ]
