# Generated by Django 2.2 on 2021-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210325_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='medinfo',
            name='diabetes',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you have diabetes?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Normal', 'I can see clearly'), ('Myopia', 'Difficult to see distant objects'), ('Hypermetropia', 'Difficult in reading'), ('Presbyopia', 'Difficulty in both'), ('Glasses', 'I wear Glasses')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('NN', "Don't remember the last time I got"), ('N', 'Once in a while'), ('S', 'Very Often')], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
    ]
