# Generated by Django 2.2 on 2021-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20210415_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medinfo',
            name='eye_sight',
            field=models.CharField(choices=[('Glasses', 'I wear Glasses'), ('Myopia', 'Difficult to see distant objects'), ('Normal', 'I can see clearly'), ('Hypermetropia', 'Difficult in reading'), ('Presbyopia', 'Difficulty in both')], default=False, max_length=20, verbose_name='How is your eye sight?'),
        ),
        migrations.AlterField(
            model_name='medinfo',
            name='fever_cycle',
            field=models.CharField(choices=[('S', 'Very Often'), ('N', 'Once in a while'), ('NN', "Don't remember the last time I got")], default=None, max_length=3, null=True, verbose_name='How often do you get cold or fever?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
